{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "7.4.2"
    }
  },
  "component" : {
    "group" : "com.github.JRJimenezReyes",
    "module" : "entrada",
    "version" : "1.0.3",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "variants" : [ {
    "name" : "apiElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "8",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-api"
    },
    "files" : [ {
      "name" : "entrada-1.0.3.jar",
      "url" : "entrada-1.0.3.jar",
      "size" : 3398,
      "sha512" : "3b463424a79d6fc5d91671a117818acb7754be619c3fb658cc344d027d66c73647b78d7ba727fb634926281230a85e21c08370b592eb1e377d5f2932bd35436c",
      "sha256" : "868542242560d8b60bccfbce0afffa9882a45b9199569887527a59721f7f7783",
      "sha1" : "a17a5e520073c8d799639e86457604179a1a39f7",
      "md5" : "ac2112ddcb23ee6a1ba9712f69fb8e8f"
    } ]
  }, {
    "name" : "runtimeElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "8",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime"
    },
    "files" : [ {
      "name" : "entrada-1.0.3.jar",
      "url" : "entrada-1.0.3.jar",
      "size" : 3398,
      "sha512" : "3b463424a79d6fc5d91671a117818acb7754be619c3fb658cc344d027d66c73647b78d7ba727fb634926281230a85e21c08370b592eb1e377d5f2932bd35436c",
      "sha256" : "868542242560d8b60bccfbce0afffa9882a45b9199569887527a59721f7f7783",
      "sha1" : "a17a5e520073c8d799639e86457604179a1a39f7",
      "md5" : "ac2112ddcb23ee6a1ba9712f69fb8e8f"
    } ]
  }, {
    "name" : "sourcesElements",
    "attributes" : {
      "org.gradle.category" : "documentation",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.docstype" : "sources",
      "org.gradle.usage" : "java-runtime"
    },
    "files" : [ {
      "name" : "entrada-1.0.3.jar",
      "url" : "entrada-1.0.3.jar",
      "size" : 1877,
      "sha512" : "e3ccc6f31f0fb49918cbaee522b833d833c8f35181a6a1c7918daff34abb43477a0d7a2aa89bf3ff6dcfb827cc3179308a9659dabf30daed77078ec0314252cf",
      "sha256" : "fbc29872c7a3054e561dce72ad4e8c06cb3f11837395b3befc84cfa56f178412",
      "sha1" : "1a4ae23b1f08db505001749d31560e9b54f5246f",
      "md5" : "82bbf24779f4002b76f4291932acc3ac"
    } ]
  }, {
    "name" : "javadocElements",
    "attributes" : {
      "org.gradle.category" : "documentation",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.docstype" : "javadoc",
      "org.gradle.usage" : "java-runtime"
    },
    "files" : [ {
      "name" : "entrada-1.0.3.jar",
      "url" : "entrada-1.0.3.jar",
      "size" : 19575,
      "sha512" : "0dcbdbad2663f96d283d7428bf8a62f057dbdbb4dd9ddbedb2694d91018895e358aec1866ed06d50ab7e69b20b89040e69aa840b23cd4024230206ab1b2e3ae4",
      "sha256" : "4700a551a960db08d7a1b16bc5bd0a706628ed2a19412f7553ae8b2fb7f9f261",
      "sha1" : "162bccce14c50f378e57626e8e4c428f19f28c3e",
      "md5" : "c32cc10562361f62f1b736c1e95c7da2"
    } ]
  } ]
}